### ISSUE TITLE
Cannot show copyright symbol in PDF files

### ISSUE THREAD

**Issue by fdbatista** [diegomura/react-pdf#2277]
**Describe the bug**
The library appears to be unable to render copyright symbols into the generated PDF file.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Try to output a copyright symbol inside of a `Text` component.
2. Generate a PDF file.
3. Nothing will be shown.

I've tried different ways without luck:
- Copying/pasting the symbol itself.
- Using the HTML entities `&#169;`, `&#xA9;`, `&copy;` .
- Using the content CSS property `content: "\00A9"`

I am using Poppins font family, but tried also with Times New Roman and got the same output.
 
**Expected behavior**
The copyright symbol should be displayed in the PDF.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome 112.0.5615.121 (Official Build) (64-bit)
 - React-pdf version: 3.1.9

**Comment by nicopollon** [comment]
I know it's not a solution but when i insert the ohm resistance symbol Ω , the rendered pdf shows a copyright symbol  instead maybe this could be a momentary solution to your problem

**Comment by SM2DevLLC** [comment]
Any update on symbols working properly? The Ω symbol for me does not work. It actually outputs the Ω symbol itself. I'm using the "montserrat" font family.

**Comment by nicopollon** [comment]
So i'm actually using the Inter Font

I've attacched some pics as proof of how the copyright symbol is rendered instead of the omega

![inter_font_register](https://github.com/diegomura/react-pdf/assets/36526066/05d8d2f7-28b2-4294-87d7-1a72474ff604)
![copyright_pdf_render](https://github.com/diegomura/react-pdf/assets/36526066/d8b51235-2b5a-44e5-880e-a1609dd91d10)
![omega_pdf_react](https://github.com/diegomura/react-pdf/assets/36526066/2065ada0-08a0-4191-ad52-74c16ab37768)

**Comment by nicopollon** [comment]
> Any update on symbols working properly? The Ω symbol for me does not work. It actually outputs the Ω symbol itself. I'm using the "montserrat" font family.

So i'm actually using the Inter Font

I've attacched some pics as proof of how the copyright symbol is rendered instead of the omega

![inter_font_register](https://github.com/diegomura/react-pdf/assets/36526066/05d8d2f7-28b2-4294-87d7-1a72474ff604)
![copyright_pdf_render](https://github.com/diegomura/react-pdf/assets/36526066/d8b51235-2b5a-44e5-880e-a1609dd91d10)
![omega_pdf_react](https://github.com/diegomura/react-pdf/assets/36526066/2065ada0-08a0-4191-ad52-74c16ab37768)

**Comment by nikels** [comment]
I'm having the same issue but with the trademark symbol, ™. I've tried html entities, unicode and into the symbol directly. I'm using a google font, Plus Jakarta San, which does render the symbol.

**Comment by SM2DevLLC** [comment]
I ended up exporting the symbol manually, making it an SVG, and using it that way. Hopefully this will get fixed at some point.

**Comment by hcharley** [comment]
@SM2DevLLC I've had to do the same. Hopefully this does get fixed, as my project has many many pages of content and it is nerve-racking to think of some symbols not rendering.

**Comment by szabinah90** [comment]
@nikels I may be a bit late for the party, but I'm struggling with the same. Inspired by the omega - copyright symbol connection, I tried the greek alphabet and the "iota" (Ι) greek character is rendered as the TM symbol, at least in the default font set. My problem was not solved, as I'm using Manrope, but may help you and others.

**Comment by marco-hd** [comment]
**@react-pdf/renderer: "^3.1.13"**

I'm using the Klavika font family, and it displays a crossed square. When I switch to the default font, it appears as empty.

Klavika
![image](https://github.com/diegomura/react-pdf/assets/118807904/c2b8616e-a671-4887-a676-a11ef927edd9)

Helvetica
![image](https://github.com/diegomura/react-pdf/assets/118807904/b2294760-ce02-4568-a3b1-2f1d074bc3ea)

P.S. Omega is working with the default fonts

**Comment by masonbrothers** [comment]
To get the copyright symbol to show, I had to use `registerEmojiSource`:

https://github.com/diegomura/react-pdf/blob/c8fe2c8/packages/examples/src/emoji/index.jsx#L16-L21
```javascript
Font.registerEmojiSource({
  format: 'png',
  url: 'https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/',
  // url: 'https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.0.1/img/apple/64/',
  // withVariationSelectors: true,
});
```

**Comment by EvHaus** [comment]
Note to others: I was having trouble with this, even after the fix in #2496. I had to switch from using `©` (\xC2\xA9) to using `©️` (\xC2\xA9\xEF\xB8\x8F).

TIL there are two different copyright symbols in UTF-8... 🤦

**Comment by AdemYuksel** [comment]
> To get the copyright symbol to show, I had to use `registerEmojiSource`:
> 
> https://github.com/diegomura/react-pdf/blob/c8fe2c8/packages/examples/src/emoji/index.jsx#L16-L21
> 
> ```js
> Font.registerEmojiSource({
>   format: 'png',
>   url: 'https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/',
>   // url: 'https://cdn.jsdelivr.net/npm/emoji-datasource-apple@15.0.1/img/apple/64/',
>   // withVariationSelectors: true,
> });
> ```
> 
> It looks like the copyright symbol ©️ is actually an emoji when it is displayed

No matter how many fonts I used.
I used all HTML entities &#169;, &#xA9;, &#xA9;, &copy; and that solved my problem. Thank you. 🌟
