### ISSUE TITLE
Wrap won't work when text is higher than the page

### ISSUE THREAD

**Issue by LivioGama** [diegomura/react-pdf#246]
Hello,

I found out that if a `<Text>` is wrapped in a `<View>`, then if the text is taller than the page, we run into an infinite loop calculation making the browser stucked and need to force quit.

[Here](http://react-pdf.diegomura.com/repl?code=3187b0760ce02e004026260c0bc300500a06300f00451015c05b014cc2803e2db5c005010c07352601dc027060076b6da700350096a4d9f7e0200aa9001e5400c880ea588c61dc209782000db2981186c0664a001a18a12296051494421c603381b84460c2c1318a5771801d0c0032a91c0c18380c0707a10430487c77391b84042b2eada3840c1432be47259b931807919a918999a5abbba7b7af982da5a12e942c57a92e465c315eb2b04030972e7faab9239a9b4770b0377c30a9b0402c832db9032e40531b430c3116c40325801b832c7c4ba586710a73b5aee925a92107b10804545825b130b05d038206f0c1b8052831994966517922b648b8048c4002781cf4dd0873cfc6535062fc5961000cd520761259be3062470c8146d1b94c910f2e90cc617198fc5c28304f06f1eaa9eedcde4b838c04201c8e27433ccb2b1080011d08ac53b19d6966b064150c583792cdc15043b492f23098800ff16428dd056b11e8ae080155b560189c572a73d210a0dc2d4c00200235210341000b0b838b8797e60c60232d8c14e18e11fadada3f5275286c213c015c6ea4cfc2c681c6b2207533a5270520e7d6190a0c0fdba06180dcb04fb094baf6c49acdba0b7d9e58ac3385e06f1827a5c59c1c369b2dc327c1859048c10489e4ee90d96f5269b47a93478cb9486210bcc9dc8c384bee3ce4fcb019a741660ad2066d8434c05f643273ac00dc3000208049a9a8651fac1aac47aca2e12087138fbaf4a0b84ac0a4bda4c56a0e548d2533811b180719d4dc0785e0f82e26e14bd2953ce8b8c0c1aa42a2c45c8601823af1bf8ac8c1b28bc8594071af4961305c32a703eccd300d0870b84a863858a4b047fb90a4136524c0e78b1cca1ce93ec5a034046c0dc1b4ca849c1000726d23673af673318841b8603040018bc4f33c617308f12583b1ec08b3af61dc5702ec2101e4a10601208e070046e4a6698a038581a32a0658208f97a4f43c288cea06201ba2aa64c22ec8d8f67d9a1ac070c1b80a2ae4603054803813b663000092968b0ce308113120112e9f970699852e2018aae9e6aa103ab0e47044d7d82d4c00abee6615ccab71ac2b1b03e87e814fba905c56cc11282a1a81a1686a020fa338551b20e1aae0064760388ab38f86118d3e2410c02b32869aa91c8fa14bb1fbb58e70596ea90c19cc7b319514de861a5e404dcd5c58521491af66e7f5016100ca124789ea8c030ba75ea1f4563804f1f88425840781b0645bdb45ca3dc94ab1d952ddf57230202c0b3ac49664b34947a9314b8c984ee597dd58bcdb91e91c15c4b28a04d64762a3b56ccd03a3b97e5fb00056f13e4f18e5e2a940c2048c401e8c3278d03e64045e238366824e3c4d59e675bf9815766a0fa1864cda07c40fb979679ea71c2e1b8115114d132b50d5bc87c5f126c1a32103329d82b393d98e52a6d1e9dc7d84387bb031c046c3cbb08e731057096b240d0cabcef27cbeba641a76c6a9a30099b4dc2480757070e25a828dbcc9cba8772066e038b27c98a5695e0e99124320b6bd008089324a93942f8705a4c49eb4b1ee4e559b790c42215b5c16c0c7d787019f324c65faf54e3a80c1cb1e3b9ca2a85f695e555c58f1e49aa3ddee443886d19b526f67bc9e0bc5bced13a2886d84fc2b9bf350e712e24b0765d4ef9596709d94c38f1c0001e8643c8090fc1f0488310c43701e0c602c0243e0820a2930b5000094df91880025052760e81e03b28105433640c68010300161400000) is the sample, just copy paste the lorem ipsum until it overlap the page !

**Comment by LivioGama** [comment]
Hello, I'm going in production with my site on Monday and I need to solve this, so I'm putting hands into it. Do you have any idea or recommendation for me where to start, or an insight of what might be wrong?

**Comment by diegomura** [comment]
Hey!
Quick question first: are you using the lib client or server side?

There were some infinite loops issues reported on pdfkit, which is the library we use to create the PDF documents. I would start debugging the react-pdf `Text` element (https://github.com/diegomura/react-pdf/blob/master/packages/react-pdf/src/elements/Text.js) and seeing if this issue is here or in that dependency. 

For development, please make sure you run `yarn build:watch` to compile the files while you edit them

**Comment by LivioGama** [comment]
Do you know how I can make the project use the src folder instead of the lib (transpiled) project ?

**Comment by LivioGama** [comment]
I use an IDE which allow me to debug with a debugger (I'm not a big fan of console.log ^^) but it need to breakpoint to meaningful lines. Anyway, meantime I actually started with console.log and the build:watch for auto compilation, and I found out some preliminary things : 
- In the `Base.js` file in the function `fillRemainingSpace` if the element is a <View> (containing long text), then canBeSplitted is false, but if it's a <Text> (containing long text), then canBeSplitted is true.
So when it's a view, there is an infinite loop in the `recalculateLayout()` ! I'm checking if I can fix it.
![capture d ecran 2018-06-21 a 14 51 49](https://user-images.githubusercontent.com/6930498/41720294-ddc07138-7562-11e8-9576-58942cbf8144.png)

**Comment by LivioGama** [comment]
Actually, it's all about [this](https://github.com/diegomura/react-pdf/blob/69ea7c8e602042c403c742e1ea5d51e52a2fcb68/packages/react-pdf/src/utils/wrapping.js#L41). A Text is splitted into 2 boxes in a way than one will go on the current page and the second on the next page. But there is no implementation of how to split a View. I'm trying to write one but it's quite hard since a View can recursively contain anything and potentially infinite depth.

**Comment by diegomura** [comment]
Haha yes. That's a problem I actually solved in branch `1.0.0`, but didn't have time to wrap that up. You can just look how it's implemented there and try fixing this version. Just to bare in mind, that branch also has a ton of other features, so you may have to separate those from the wrapping algorithm

**Comment by LivioGama** [comment]
Oh I didn't see the branch `1.0.0`. But I tested this branch, and there is no infinite loop but it takes a lot of time (11 sec) and it is not working!
![capture d ecran 2018-06-22 a 11 04 11](https://user-images.githubusercontent.com/6930498/41768291-1158e2d8-760c-11e8-868e-fd9b232f8a64.png)

**Comment by LivioGama** [comment]
But I think I fixed it (unfortunately on the branch master :( ). 
I need to run some tests in my project which has a more complex structure before submitting any pull request.
![capture d ecran 2018-06-22 a 11 09 00](https://user-images.githubusercontent.com/6930498/41768580-ea4d0a9c-760c-11e8-9004-6c2ebc0de636.png)

**Comment by diegomura** [comment]
Awesome!
`1.0.0` branch is still a WIP. No guarantees at all about how that work, but it does work good for some scenarios. It's odd it didn't work on that. Will test it eventually

**Comment by LivioGama** [comment]
I'm trying to use the project directly from my GitHub where I forket in order to test, but do you know how I could point to the @react-pdf/core of my GitHub ? When I `npm install --save https://github.com/LivioGama/react-pdf.git` it doesn't find the core project (not surprising!)

**Comment by LivioGama** [comment]
What I did work with Text, but if I nest an Image and a Text in the View, I have problems that I can't solve. With a bit of adaptation, the image and the Text will display in a flow, the text being splitted correctly, but the second portion of Text won't have a proper height due to Yoga async calculation nature.

I think this lib is not for me because the best way to produce a wrapped Page is with a strategy of rendering next child (but tiny child), and if it will overlap the page then place it on the next page. But you can't do that with a View or nested elements. And you can't do without Views due to React nature of forcing you to return only one child. So this lib is for simple and flat architecture of PDF but not for complex nested layout.

**Comment by diegomura** [comment]
@LivioGama sorry to hear that. My goal is to make this lib not for simple and flat layouts, but the stable version just does not support it. All my work is going to be focused on the `v1.0.0` branch, but I simply didn't have enough time to finish it. But believe me, that branch already support complex layouts (I implemented myself for a couple of companies) Hopefully one day this lib may suit your needs!

**Comment by dsvictor94** [comment]
This bug still happen? I have tried a long text at [this repl](https://react-pdf.org/repl?code=198570760c602e0960f66001009c0866039814c014c65c02d80348947009403780508a2102033948803630b880bc880da0174ea200ee002c61b5cf88a2003c652a25af5e871600e8003882662f014201a88c561017d8722c5043224eaa0d4b351982e0104b569e887051e003e3f61390011380810422c302840e17a390005546c04d555390035182c11440cccc400483900152c000f78aa344c5c000652000e46c68a0d42542d1c2aa0c40072282c2e418a7339007a4a9aa2cce9dcfcf9f929d4f4d0a988a898b8848a006e1a6380252c546864b080310d6b3000132c641c392f1f29c0c39a20000) and got a white page.
