### ISSUE TITLE
Syntax error: 'import' and 'export' may appear only with 'sourceType: module' (1:0)

### ISSUE THREAD

**Issue by xavibalderas** [diegomura/react-pdf#264]
**OS:MacOS 10.12.6**

**React-pdf version:1.0.0-alpha.8**
**React version:16.4.1**

**Description: trying to replicate the REPL approach from the site when using the PDFRenderer it doesn't compile showing this error message for the file fontkit.browser.es.js and pdfkit.browser.er.js**

It seems to be a problem with babel, any idea on how to solve it? The project has been created with create-react-app and I added in the webconfig file the babel-polyfill to solve other issues.

Thanks for your help!!!!

**Comment by diegomura** [comment]
Can you provide your webpack config?

**Comment by ybbond** [comment]
also happened to me, to me, this happened after I added the configuration that mentioned on issue thread https://github.com/diegomura/react-pdf/issues/210 that said will fix other issue.

before I implement the fix (by installed `transform-loader` and added some lines in my webpack-config-dev.js), an error of "fs.readFileSync is not a function" happened after I tried to render to file using `@react-pdf/node` and ReactPDF.render(). but after I implemented the fix, the same error message as this topic happened.

```const autoprefixer = require('autoprefixer');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin');
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
const eslintFormatter = require('react-dev-utils/eslintFormatter');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');
const getClientEnvironment = require('./env');
const paths = require('./paths');
const publicPath = '/';
const publicUrl = '';
const env = getClientEnvironment(publicUrl);

module.exports = {
  devtool: 'cheap-module-source-map',
  entry: [
    require.resolve('./polyfills'),
    require.resolve('react-dev-utils/webpackHotDevClient'),
    paths.appIndexJs,
  ],
  output: {
    pathinfo: true,
    filename: 'static/js/bundle.js',
    chunkFilename: 'static/js/[name].chunk.js',
    publicPath: publicPath,
    devtoolModuleFilenameTemplate: (info) =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
  resolve: {
    modules: ['node_modules', paths.appNodeModules].concat(
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean),
    ),
    extensions: ['.web.js', '.mjs', '.js', '.json', '.web.jsx', '.jsx'],
    alias: {
      'react-native': 'react-native-web',
    },
    plugins: [
      new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
    ],
  },
  module: {
    strictExportPresence: true,
    rules: [
      {
        test: /\.(js|jsx|mjs)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
              eslintPath: require.resolve('eslint'),
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      {
        oneOf: [
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: 10000,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
          {
            test: /\.(js|jsx|mjs)$/,
            include: paths.appSrc,
            loader: require.resolve('babel-loader'),
            options: {
              cacheDirectory: true,
            },
          },
          {
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9',
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },
          {
            exclude: [/\.js$/, /\.html$/, /\.json$/],
            loader: require.resolve('file-loader'),
            options: {
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
        ],
      },
      // I added these two below because one user in other issue thread said so.
      // https://github.com/diegomura/react-pdf/issues/210
      {
        test: /(pdfkit|linebreak|fontkit|unicode|brotli|png-js).*\.js$/,
        loader: 'transform-loader?brfs',
      },
      {
        test: /\.pdf$/,
        loader: 'url-loader',
      },
    ],
  },
  plugins: [
    new InterpolateHtmlPlugin(env.raw),
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin(env.stringified),
    new webpack.HotModuleReplacementPlugin(),
    new CaseSensitivePathsPlugin(),
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
  ],
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty',
  },
  performance: {
    hints: false,
  },
};
```

**Comment by diegomura** [comment]
@ybbond  just in case, with the new version of react-pdf (which is also in a separate package `@react-pdf/react-pdf just in case), you should not shim `test: /(pdfkit|linebreak|fontkit|unicode|brotli|png-js).*\.js$/,` dependencies, nor add the ` node: { XXX: 'empty' }` configs. 

I don't think it's related to this issue, but I think it's important to know. Going to study the cause of this soon

**Comment by jennysharps** [comment]
@diegomura I am on @react-pdf/react-pdf 1.0.0-alpha.8 and still get the error:

```
TypeError: fs.readFileSync is not a function
```

when I don't add the shim you're mentioned.  Should that not be the case?

I arrived at this issue because I'm getting the exact error as @ybbond by the way

**Comment by diegomura** [comment]
I just read again @ybbond comment and I found one issue: you should not use ‘@react-pdf/node’ binding anymore. Everything is packed in ‘@react-pdf/react-pdf’ now. Are you using it?

**Comment by diegomura** [comment]
I just published a new version `1.0.0-alpha.11`. Can you test it and check if the issue persist? You should not need `babel-polyfill` in this one also

cc/ @ybbond @xavibalderas

**Comment by ybbond** [comment]
yeah, I tried using latest version of `1.0.0-alpha.12` and I am not required to import `babel-polyfill`. great work!

did you just update the dependencies and removing fonts for the update from alpha 8 to alpha 12?

**Comment by jennysharps** [comment]
@diegomura thanks for the info! I have it working now with the single @react-pdf/react-pdf repo.

@ybbond I'm attempting something similar, but am unable to accomplish it as I can't access the src for the iframe -- when I select the iframe from the document, trying to access src returns undefined.  Were you able to actually access the data url?

It would be really helpful if Document's onRender function was passed some relevant details about the document -- ie, the blob url!

**Comment by ybbond** [comment]
I am guessing that the onRender method executed when the `<Container />` component aka `<Document />` component successfully rendered, the `blob:[url]` reference to the data is there, but I am guessing that it is not fully a PDF data yet.
my method *was* kinda hacky and blocking as I generate the pdf data on the front end and pass it to cloudinary's upload API.
here, maybe my method can give you insight:
```
<MfcEcontract
  onRender={() => {
    setTimeout(() => {
      let iframe = document.getElementsByTagName('iframe')[1];
      let xhr = new XMLHttpRequest();
      xhr.open('GET', iframe.src, true);
      xhr.responseType = 'blob';
      xhr.onload = function(e) {
        if (this.status === 200) {
          let fileData = this.response;
          onUploadRequest(fileData);
        }
      };
      xhr.send();
    });
  }}
  {...eContractProps}
/>
```

my knowledge is kinda limited myself, but I am guessing that the setTimeout without milliseconds parameter makes it async *or* execute it just a tick after the pdf data is there.

**Comment by diegomura** [comment]
> did you just update the dependencies and removing fonts for the update from alpha 8 to alpha 12?

No. It also includes some layout fixes and new features

> It would be really helpful if Document's onRender call were passed some relevant details about the document -- ie, the blob url!

@jennysharps do you mind create a new issue for this

Can we close this issue now?
Thanks y'all!

**Comment by jennysharps** [comment]
@diegomura sounds good, I will try to raise one shortly just a bit busy this week!
