### ISSUE TITLE
TypeError: qo is not a function

### ISSUE THREAD

**Issue by JacobWeisenburger** [diegomura/react-pdf#2978]
Every time I save I get this error: `TypeError: qo is not a function`

![image](https://github.com/user-attachments/assets/55022f66-e43b-475f-93af-e7a6c28a62a7)

Then I have to reload the page and everything works again until I save again.

---

Here's the full error stack.
```
TypeError: qo is not a function
    at ml (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:3425:155)
    at Ol (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:3917:25)
    at Ml (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:3845:29)
    at Hl (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:3860:21)
    at ga (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:4428:35)
    at http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:4395:38
    at pa (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:4396:18)
    at Yl (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:4109:13)
    at $l (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:4096:29)
    at Re (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:916:31)
    at Ce (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:866:92)
    at Ya.flushSyncWork (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:5540:48)
    at Object.updateContainer (http://localhost:3000/_next/static/chunks/node_modules_@react-pdf_reconciler_lib_cdf250._.js:5614:50)
    at Object.updateContainer (http://localhost:3000/_next/static/chunks/node_modules_ea10b4._.js:19011:18)
    at usePDF.useCallback[update] (http://localhost:3000/_next/static/chunks/node_modules_ea10b4._.js:19220:33)
    at PDFViewer.useEffect (http://localhost:3000/_next/static/chunks/node_modules_ea10b4._.js:19232:36)
    at react-stack-bottom-frame (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:12439:22)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at commitHookEffectListMount (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:5817:628)
    at commitHookPassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:5852:60)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6756:33)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
```

**Comment by AtheerAPeter** [comment]
same here, happening since i updated to next 15

**Comment by JacobWeisenburger** [comment]
Still getting the same error after updating to [`@react-pdf/renderer: 4.1.5`](https://www.npmjs.com/package/@react-pdf/renderer/v/4.1.5)

![image](https://github.com/user-attachments/assets/0589b5b8-f9f7-4371-b3e8-6ee1b458b843)


```ts
"dependencies": {
    "@react-pdf/renderer": "^4.1.5",
    "next": "15.0.3",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106"
},
"devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
}
```

```
TypeError: qo is not a function
    at ml (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:3425:155)
    at Ol (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:3917:25)
    at Ml (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:3845:29)
    at Hl (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:3860:21)
    at ga (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:4428:35)
    at http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:4395:38
    at pa (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:4396:18)
    at Yl (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:4109:13)
    at $l (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:4096:29)
    at Re (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:916:31)
    at Ce (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:866:92)
    at Ya.flushSyncWork (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:5540:48)
    at Object.updateContainer (http://localhost:3000/_next/static/chunks/9037f_@react-pdf_reconciler_lib_3be79f._.js:5614:50)
    at Object.updateContainer (http://localhost:3000/_next/static/chunks/node_modules_efa1a4._.js:19011:18)
    at usePDF.useCallback[update] (http://localhost:3000/_next/static/chunks/node_modules_efa1a4._.js:19220:33)
    at PDFViewer.useEffect (http://localhost:3000/_next/static/chunks/node_modules_efa1a4._.js:19232:36)
    at react-stack-bottom-frame (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:12439:22)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:631:20)
    at commitHookEffectListMount (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:5817:628)
    at commitHookPassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:5852:60)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6756:33)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6789:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
    at commitPassiveMountOnFiber (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6755:17)
    at recursivelyTraversePassiveMountEffects (http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:6747:106)
```

**Comment by evertjr** [comment]
I'm getting this error too on Next 15. Any idea what triggers this and there's any workaround?

**Comment by pironti** [comment]
Same here using next 15 with react 19. Any ideias?

**Comment by vishnut2003** [comment]
This error is because of change in state. I fixed it by doing conditional rendering.

**Comment by evertjr** [comment]
I downgraded the project to Next 14 in the meantime and it stoped the problem, so it is clearly some incompatibility with Next 15 / React 19

**Comment by JacobWeisenburger** [comment]
> This error is because of change in state. I fixed it by doing conditional rendering.

Could you and a code example of what you mean?

**Comment by alanhaertel** [comment]
Same error here. Using NextJS 15.1.0 with stable React 19 version and @react-pdf/renderer: 4.1.5

**Comment by rmondi** [comment]
Hello everybody !

I'm facing this problem too.

Is there any solution to this problem ?

> This error is because of change in state. I fixed it by doing conditional rendering.

@vishnut2003 Can you please provide a example ?

**Comment by kanarian** [comment]
This worked for me:

```ts
typeof window !== 'undefined' && ( // Only render on client side
            <PDFViewer width="100%" height="100%">
              <ResumePDF data={data} />
            </PDFViewer>
          )}```

**Comment by rmondi** [comment]
Hello @kanarian, thanks for your answer but it didn't helped me.

I solved the problem by importing PDFViewer dynamically in order to prevent module to be imported on server side : https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic

PDFViewer.tsx :
`import { PDFViewer } from "@react-pdf/renderer";
export default PDFViewer;`

page.tsx :
`import dynamic from "next/dynamic";
import MyDocument from "@/app/components/MyDocument/MyDocument";

const PDFViewer = dynamic( () => import( "@/app/components/PDFViewer/PDFViewer" ), {
  loading: () => <Loader fullscreen={ true } />,
  ssr: false
} );

const Home = () => {
  return (
    <PDFViewer width="100%" height="100%">
      <MyDocument />
    </PDFViewer>
  )
}`

Hope this will help !

**Comment by samadhi1311** [comment]
I recreated the issue [here](https://stackblitz.com/edit/stackblitz-starters-gqbuxfwj)

So, What I'm trying to do here is to render <PDFDownloadLink> based on the selected template. But as soon as I change the template I get this error.

**Comment by jakiestfu** [comment]
Bump, this is an issue for us too

**Comment by michel-jump** [comment]
This is also an issue for me. I am using `PDFDownloadLink`. First time loading the page, no problem, but navigating to another page and back, it gives the same error.

**Comment by SebastienBrun** [comment]
Did you try : 

```
import dynamic from "next/dynamic";


const PDFViewer = dynamic(
  () => import("@react-pdf/renderer").then((mod) => mod.PDFViewer),
  {
    ssr: false,
    loading: () => <p>Loading...</p>,
  },
);
```

**Comment by samadhi1311** [comment]
> I have nextJS 15 and react 19. Did you try :
> 
> ```
> import dynamic from "next/dynamic";
> 
> 
> const PDFViewer = dynamic(
>   () => import("@react-pdf/renderer").then((mod) => mod.PDFViewer),
>   {
>     ssr: false,
>     loading: () => <p>Loading...</p>,
>   },
> );
> ```

This works without any issues. Thank you for sharing!

**Comment by michel-jump** [comment]
> I have nextJS 15 and react 19. Did you try :
> 
> ```
> import dynamic from "next/dynamic";
> 
> 
> const PDFViewer = dynamic(
>   () => import("@react-pdf/renderer").then((mod) => mod.PDFViewer),
>   {
>     ssr: false,
>     loading: () => <p>Loading...</p>,
>   },
> );
> ```

I tried it, but you need to set `experimental.esmExternals` to `loose`.
How save is it to run that in production?

**Comment by mouchegmouradian** [comment]
> This is also an issue for me. I am using `PDFDownloadLink`. First time loading the page, no problem, but navigating to another page and back, it gives the same error.

@michel-jump Here is how I "fixed it": https://github.com/diegomura/react-pdf/pull/2888#issuecomment-2547389099

**Comment by SebastienBrun** [comment]
You right, i had issue too. 
Finally what i did is : 

Remove loose from my nextjs config (turbo pack doesn't support it)

I create a file pdfViewer.tsx with only these line : 

```
import { PDFViewer } from "@react-pdf/renderer";

export default PDFViewer;
```

Then I create a new file Exemple.tsx and import it as follow : 
```
import dynamic from "next/dynamic";
const PDFViewer = dynamic(() => import("../testpdf/pdfViewer"), {
  ssr: false,
});
  return (
    <div>
      <PDFViewer style={{ width: "100%", height: "100vh" }}>
<MyDocument />
      </PDFViewer>
    </div>
  );

```

The following path is where is your pdfViewer.tsx ../testpdf/pdfViewer

**Comment by michel-jump** [comment]
> > This is also an issue for me. I am using `PDFDownloadLink`. First time loading the page, no problem, but navigating to another page and back, it gives the same error.
> 
> @michel-jump Here is how I "fixed it": [#2888 (comment)](https://github.com/diegomura/react-pdf/pull/2888#issuecomment-2547389099)

Yeah, that's the linting part, but the `TypeError: qo is not a function` doesn't show in the lint. It only bubbles up when navigating back to the page with the `PDFDownloadLink` element.

**Comment by mouchegmouradian** [comment]
Oh right my bad, read through it too quickly. Had the same issue. I ended up removing the download button...

**Comment by michel-jump** [comment]
> You're right, i had issue too. Finally what i did :
> 
> Remove loose from my nextjs config (turbo pack doesn't support it)
> 
> I create a file pdfViewer.tsx with only these line :
> 
> ```
> import { PDFViewer } from "@react-pdf/renderer";
> 
> export default PDFViewer;
> ```
> 
> Then I create a new file Exemple.tsx and import it as follow :
> 
> ```
> import dynamic from "next/dynamic";
> const PDFViewer = dynamic(() => import("../testpdf/pdfViewer"), {
>   ssr: false,
> });
>   return (
>     <div>
>       <PDFViewer style={{ width: "100%", height: "100vh" }}>
> <MyDocument />
>       </PDFViewer>
>     </div>
>   );
> ```
> 
> The following path "../testpdf/pdfViewer" is where is your pdfViewer.tsx

Craziest thing is: I had that solution implemented before my first comment here.. It consistently gave me the error.
But somehow, I now only get the error the first time after a dev build with this solution..
It beats me..

**Comment by SebastienBrun** [comment]
ha ha ha, i do understand !

Did you try to do a very simple document PDF for the begining ?
Because sometime it is hard to know if this is the nextjs config or if it is the PDF document

**Comment by michel-jump** [comment]
> ha ha ha, i do understand !
> 
> Did you try to do a very simple document PDF for the begining ? Because sometime it is hard to know if this is the nextjs config or if it is because of the PDF document

Yes I have removed all the possible problematic stuff. Now the document is very simple. It is a View with 3 Text objects.

Where should I look for in the NextJS config?

**Comment by SebastienBrun** [comment]
I did a test for you, Let me share my config because, it works for me.

package.json : 

```
    "@react-pdf/renderer": "^4.1.6",
     "react": "19.0.0",
    "react-dom": "19.0.0",
"next": "15.1.3",
```

Next config : 

```
const nextConfig = {

  reactStrictMode: false,

  experimental: {
    turbo: {
      rules: {
        '*.svg': {
          loaders: ['@svgr/webpack'],
          as: '*.js'
        }
      },
    }
  },

  //Use for the BUILD PROD
  webpack(config) {
    // Grab the existing rule that handles SVG imports
    const fileLoaderRule = config.module.rules.find((rule) =>
      rule.test?.test?.('.svg'),
    );

    config.module.rules.push(
      // Convert all other *.svg?icon imports to React components
      {
        test: /\.svg$/i,
        issuer: /\.[jt]sx?$/,
        resourceQuery: /icon/, // *.svg?icon
        use: ['@svgr/webpack'],
      },
      // Reapply the existing rule, for all other *.svg imports
      {
        ...fileLoaderRule,
        test: /\.svg$/i,
        resourceQuery: { not: /icon/ }, // exclude if *.svg?icon
      },
    );

    // Modify the file loader rule to ignore *.svg, since we have it handled now.
    fileLoaderRule.exclude = /\.svg$/i;

    return config;
  },

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "i.giphy.com",
      },
    ],
  },
};

export default nextConfig;
```

```
"use client";

import dynamic from "next/dynamic";

import { Text, View, Document, Page } from "@react-pdf/renderer";


const PDFViewer = dynamic(() => import("./pdfViewer"), {
  ssr: false
});


export default function PagePDF() {

  

  return (
    <div>
      <PDFViewer style={{ width: "100%", height: "100vh" }}>

      <Document><Page><View><Text>Test</Text></View></Page></Document>

      </PDFViewer>
    </div>
  );
}

```

**Comment by michel-jump** [comment]
Much appreciated @SebastienBrun! I am going to debug with those settings.

**Comment by samadhi1311** [comment]
Thank you @SebastienBrun! I was able to use your method to fix my issue. I can confirm this works on **static export** which I deployed to **Cloudflare Pages**.

Here's the result: [A small project I'm working on.](https://custom-templates.hyperbooks.pages.dev/test)

**Comment by SebastienBrun** [comment]
Great!

**Comment by samadhi1311** [comment]
Thank you @SebastienBrun !! 🖤🖤

**Comment by marviobezerra** [comment]
Facing the same issue.

**Comment by kanarian** [comment]
I fixed my errors by removing the `PDFDownloadLink` component and recreating its functionality by using the following handler:

```ts
const handleDownload = async () => {
    let url = "";
    try {
      const blob = await pdf(<ResumePDF data={resumeData} />).toBlob();
      url = URL.createObjectURL(blob);

      const response = await fetch(url);
      const blobData = await response.blob();
      const blobUrl = window.URL.createObjectURL(blobData);

      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `resume-${Date.now()}.pdf`;
      link.click();

    } catch (error) {
      console.error("Error in download process:", error);
    } finally {
      if (url) URL.revokeObjectURL(url);
    }
```

**Comment by techCodeSB** [comment]
> I fixed my errors by removing the `PDFDownloadLink` component and recreating its functionality by using the following handler:
> 
> ```ts
> import { pdf } from "@react-pdf/renderer";
> 
> const handleDownload = async () => {
>     let url = "";
>     try {
>       const blob = await pdf(<ResumePDF data={resumeData} />).toBlob();
>       url = URL.createObjectURL(blob);
> 
>       const response = await fetch(url);
>       const blobData = await response.blob();
>       const blobUrl = window.URL.createObjectURL(blobData);
> 
>       const link = document.createElement("a");
>       link.href = blobUrl;
>       link.download = `resume-${Date.now()}.pdf`;
>       link.click();
> 
>     } catch (error) {
>       console.error("Error in download process:", error);
>     } finally {
>       if (url) URL.revokeObjectURL(url);
>     }
> ```

Thanks brother

**Comment by marviobezerra** [comment]
Im having this problem on re-render.

**Comment by kevinrss01** [comment]
I still have the issue even with dynamic import.

For me, the issue appears only when I map different views on an array, for example:

```
rows.map((row, index) => (
                  <View
                    key={'index'}
                    style={[
                      styles.tableRow,
                      {
                        backgroundColor: getBackgroundColorByImpact(0),
                      },
                    ]}
                  >
                    <Text style={{ ...styles.cell, flex: 2 }}>
                      {row.question}
                    </Text>
                  </View>
                ))
```

Do you have any clue?

**Comment by samadhi1311** [comment]
> I still have the issue even with dynamic import.
> 
> For me, the issue appears only when I map different views on an array, for example:
> 
> ```
> rows.map((row, index) => (
>                   <View
>                     key={'index'}
>                     style={[
>                       styles.tableRow,
>                       {
>                         backgroundColor: getBackgroundColorByImpact(0),
>                       },
>                     ]}
>                   >
>                     <Text style={{ ...styles.cell, flex: 2 }}>
>                       {row.question}
>                     </Text>
>                   </View>
>                 ))
> ```
> 
> Do you have any clue? (I do not use `PDFDownloadLink `)

I have used both PDFViewer and PDFDownloadLink [here](https://github.com/samadhi1311/hyperbooks/blob/main/app/(index)/test/page.tsx). Take a look

**Comment by s-deSilence** [comment]
I have this problem too. React 19.0.0
Issue appears when I use && operator for conditional render and content should dissapear or when I remove some element from array map.

`{ telegram && (  <Text style={styles.someStyles}>{telegram}</Text>)}`
or
`{ employments.map((employment, idx) => (<View key={idx} style={styles.someStyles}>{employment}</View>))}`

**Comment by sanjaybora04** [comment]
I was mapping some data and using some value as key, i changed the key to index of the array and it worked✅

**Comment by sanjaybora04** [comment]
So, initially its working but if you update the document in runtime, it throws this error

What i am doing is, i am reloading the whole component whenever theres any change in the document
this is not the best solution but it works.✅

**Comment by abrunner94** [comment]
The solution for Next.js and state updates is to re-render the component.

One way to do this is use with a `useEffect` that keeps track of whenever the document changes with state updates.

Here is a solution using the following package versions alongside Next.js.

I am using `zustand` for state updates.

**Packages**
```
"next": "15.1.6",
"react": "^19.0.0",
"react-dom": "^19.0.0",
"@react-pdf/renderer": "^4.1.6",
"zustand": "^5.0.3"
  ```

```typescript
'use client';

import { MinimalTemplate } from "@/app/templates/minimal-template";
import { useResumeStore } from "@/stores/resume";
import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";

const templates: Template[] = [
    { id: 'modern', name: 'Modern', component: ModernTemplate },
    { id: 'minimal', name: 'Minimal', component: MinimalTemplate }
];

const PDFViewer = dynamic(
    () => import("@react-pdf/renderer").then((mod) => mod.PDFViewer),
    {
        ssr: false,
        loading: () => <p>Loading...</p>,
    },
);

export default function BuilderPage() {
    const [key, setKey] = useState(0); // Add key for forcing remount

    // Get resumeData and updateResumeData from Zustand store
    const resumeData = useResumeStore((state) => state.resumeData);
    const updateResumeData = useResumeStore((state) => state.updateResumeData);

    const TemplateComponent = templates.find(t => t.id === selectedTemplate)?.component || templates[0].component;

    const handleFormChange = (newData: ResumeData) => {
        updateResumeData(newData);
    };

    // Update key when resumeData changes to force PDFViewer remount
    useEffect(() => {
        setKey(prev => prev + 1);
    }, [resumeData]);

    const PDFViewerComponent = () => (
        <PDFViewer showToolbar={false} className="w-full h-full">
            <TemplateComponent resumeData={resumeData} />
        </PDFViewer>
    );

    return (
        <div className="mx-auto flex flex-col h-full w-full max-h-dvh overflow-y-scroll  bg-white p-8 border-t-8 border-t-neutral-200">
            {/* Key prop forces remount when resumeData changes */}
            <div key={key} className="w-full h-full">
                <PDFViewerComponent />
            </div>
        </div>
                
    );
}
```

**Comment by deKadir** [comment]
In my case,
i use `map` function to render list items.

when i remove an element from the list, this error appears.
I think there is a issue with unmount

**Comment by kevinrss01** [comment]
> The solution for Next.js and state updates is to re-render the component.
> 
> One way to do this is use with a `useEffect` that keeps track of whenever the document changes with state updates.
> 
> Here is a solution using the following package versions alongside Next.js.
> 
> I am using `zustand` for state updates.
> 
> **Packages**
> 
> ```
> "next": "15.1.6",
> "react": "^19.0.0",
> "react-dom": "^19.0.0",
> "@react-pdf/renderer": "^4.1.6",
> "zustand": "^5.0.3"
> ```
> 
> 'use client';
> 
> import { MinimalTemplate } from "@/app/templates/minimal-template";
> import { useResumeStore } from "@/stores/resume";
> import dynamic from "next/dynamic";
> import { useEffect, useRef, useState } from "react";
> 
> const templates: Template[] = [
>     { id: 'modern', name: 'Modern', component: ModernTemplate },
>     { id: 'minimal', name: 'Minimal', component: MinimalTemplate }
> ];
> 
> const PDFViewer = dynamic(
>     () => import("@react-pdf/renderer").then((mod) => mod.PDFViewer),
>     {
>         ssr: false,
>         loading: () => <p>Loading...</p>,
>     },
> );
> 
> export default function BuilderPage() {
>     const [key, setKey] = useState(0); // Add key for forcing remount
> 
>     // Get resumeData and updateResumeData from Zustand store
>     const resumeData = useResumeStore((state) => state.resumeData);
>     const updateResumeData = useResumeStore((state) => state.updateResumeData);
> 
>     const TemplateComponent = templates.find(t => t.id === selectedTemplate)?.component || templates[0].component;
> 
>     const handleFormChange = (newData: ResumeData) => {
>         updateResumeData(newData);
>     };
> 
>     // Update key when resumeData changes to force PDFViewer remount
>     useEffect(() => {
>         setKey(prev => prev + 1);
>     }, [resumeData]);
> 
>     const PDFViewerComponent = () => (
>         <PDFViewer showToolbar={false} className="w-full h-full">
>             <TemplateComponent resumeData={resumeData} />
>         </PDFViewer>
>     );
> 
>     return (
>         <div className="mx-auto flex flex-col h-full w-full max-h-dvh overflow-y-scroll  bg-white p-8 border-t-8 border-t-neutral-200">
>             {/* Key prop forces remount when resumeData changes */}
>             <div key={key} className="w-full h-full">
>                 <PDFViewerComponent />
>             </div>
>         </div>
>                 
>     );
> }

This solution worked for me.  
I have this error when I use conditional rendering depending on a variable, for example:

`const isHidden = name === firstName`

When I move this variable into a useState or useEffect, the error disappears.

**Comment by OmPrakashBITCS** [comment]
You can use `key={Math.random}` it will basically fix this issue

**Comment by fidaay** [comment]
> You can use `key={Math.random}` it will basically fix this issue

Thank you, this is working.

```
<PDFViewer key={Math.random()}>
  <Document />
</PDFViewer>
```

**Comment by OmPrakashBITCS** [comment]
@fidaay Give a like sir. or you can also follow this https://github.com/samnickgammer

**Comment by Trosterud** [comment]
Having the same issue with usePDF. We generate a pdf in a useEffect like this:

  const [pdf, updatePdf] = usePDF({
    document: <div>Loading...</div>,
  });

  useEffect(() => {
    if (!item) return;
    updatePdf(<GeneratedPDF item={item} />);
  }, [item, updatePdf]);


And get a very silimar error: Go is not a function

Any ideas on how to fix or get around it?

**Comment by maiconsanson** [comment]
I've managed this with a simple setup: a single download button, using `Next 15.1.7` and `React 19.0.0`.

```jsx
import { pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver"; // 1.6k gziped

function PdfDownloadButton() {
  const [pdfBlob, setPdfBlob] = useState(null);

  const handleDownload = () => {
    if (pdfBlob) saveAs(pdfBlob, "file.pdf");
  };

  // Pre-generating the PDF on component mount to improve download speed
  useEffect(() => {
    const generatePdf = async () => {
      const doc = <MyDocument someData="hellor" />;
      const blob = await pdf(doc).toBlob();
      setPdfBlob(blob);
    };

    generatePdf();
  }, []);

  return (
    <button
      disabled={!pdfBlob}
      // Using onMouseDown instead of onClick to trigger the download slightly faster
      onMouseDown={handleDownload}
    >
      {pdfBlob ? "Download" : "Loading"}
    </button>
  );
}

```

**Comment by garand** [comment]
I also am running into this when the array length gets smaller. I'm using TanStack Query for the data, so I set my key to `query.dataUpdatedAt` and it seems to be working fine now.

**Comment by MinyoungRsup2** [comment]
> Having the same issue with usePDF. We generate a pdf in a useEffect like this:
> 
> ```
>   const [pdf, updatePdf] = usePDF({
>     document: <div>Loading...</div>,
>   });
> 
>   useEffect(() => {
>     if (!item) return;
>     updatePdf(<GeneratedPDF item={item} />);
>   }, [item, updatePdf]);
> ```
> 
> And get a very silimar error: Go is not a function
> 
> Any ideas on how to fix or get around it?

@Trosterud 
I had the exact same pattern, with the same problem as above. Idk how but I fixed it by initializing the document to null. I'm suspicious of the fact that maybe the document get cached? and update function doesn't trigger a rerender properly. Have to do look at the original code to really understand but this works for now.

```
const [instance, update] = usePDF({
    document: null,
  });
```

**Comment by justnixx** [comment]
I spent an entire day troubleshooting this issue, trying every suggested solution I could find—but nothing worked.  

### **The Problem**  
I have a form on the left for filling out an invoice and a **PDF preview** (using `PDFViewer`) on the right. Everything updates in sync when I **add** or **edit** a line item. However, when I **remove** a line item, I get the runtime error:  

```
Error: qo is not a function
```  

When I saw @deKadir's response, I had hope since I was facing the same issue. I also tried @abrunner94’s solution, but for some reason, it still didn’t work.  

### **The Fix**  

I made **two key changes** that finally resolved the issue:  

1. **Avoid using `index` as the key** when rendering line items in the invoice template. Using an index can cause unpredictable behavior, especially when items are re-ordered or removed. Instead, I assigned each line item a **unique ID** using a utility function:  

   ```tsx
   export type InvoiceLineItem = {
     id: string;
     description: string;
     quantity: string;
     price: string;
   };

   const [lineItems, setLineItems] = useState<InvoiceLineItem[]>([
     {
       id: uniqueString(),
       description: '',
       quantity: '1',
       price: '',
     },
   ]);
   ```

2. **Force re-rendering of `PDFViewer`** when the line items change.  
   I wrapped the `PDFViewer` in a `<div>` and set its `key` to the **length of the lineItems array**. This ensures that whenever an item is removed, React fully re-renders the PDF preview instead of trying to reconcile changes incorrectly:  

   ```tsx
   <div key={lineItems.length} className="w-full h-[90%] min-h-96 overflow-hidden">
     <PDFViewer showToolbar={false} className="w-full h-full">
       <InvoiceTemplate data={{ ...InvoiceData, items: lineItems }} />
     </PDFViewer>
   </div>
   ```

I hope this saves someone else the frustration I went through! 🚀

**Comment by Sowishi** [comment]
> I spent an entire day troubleshooting this issue, trying every suggested solution I could find—but nothing worked.
> 
> ### **The Problem**
> I have a form on the left for filling out an invoice and a **PDF preview** (using `PDFViewer`) on the right. Everything updates in sync when I **add** or **edit** a line item. However, when I **remove** a line item, I get the runtime error:
> 
> ```
> Error: qo is not a function
> ```
> 
> When I saw [@deKadir](https://github.com/deKadir)'s response, I had hope since I was facing the same issue. I also tried [@abrunner94](https://github.com/abrunner94)’s solution, but for some reason, it still didn’t work.
> 
> ### **The Fix**
> I made **two key changes** that finally resolved the issue:
> 
> 1. **Avoid using `index` as the key** when rendering line items in the invoice template. Using an index can cause unpredictable behavior, especially when items are re-ordered or removed. Instead, I assigned each line item a **unique ID** using a utility function:
>    export type InvoiceLineItem = {
>      id: string;
>      description: string;
>      quantity: string;
>      price: string;
>    };
>    
>    const [lineItems, setLineItems] = useState<InvoiceLineItem[]>([
>      {
>        id: uniqueString(),
>        description: '',
>        quantity: '1',
>        price: '',
>      },
>    ]);
> 2. **Force re-rendering of `PDFViewer`** when the line items change.
>    I wrapped the `PDFViewer` in a `<div>` and set its `key` to the **length of the lineItems array**. This ensures that whenever an item is removed, React fully re-renders the PDF preview instead of trying to reconcile changes incorrectly:
>    <div key={lineItems.length} className="w-full h-[90%] min-h-96 overflow-hidden">
>      <PDFViewer showToolbar={false} className="w-full h-full">
>        <InvoiceTemplate data={{ ...InvoiceData, items: lineItems }} />
>      </PDFViewer>
>    </div>
> 
> I hope this saves someone else the frustration I went through! 🚀

**Comment by Mpadilhat** [comment]
### I had the same problem, but using **PDFDownloadLink**.

In my case, the application had translation and the error occurred when **changing the language** selector (which **updated the PDF content in real time**).

Basically **I was using a translation hook inside my PDF** component and I solved it like this:

> **1. I added a unique key to PDFDownloadLink (language selected);**
> **2. I removed the hook from within the PDF and gave it the translation function as a prop.**

**1. Unique key:**
```
...
<PDFDownloadLink
    key={currentLanguage}
    style={{ textDecoration: 'none' }}
     document={ 
        <ReceiptPdf 
            paymentData={successfulPayment}
            formatValueToMonetary={formatValueToMonetary}
            formatDate={formatDatePDF}
            translator={translator}
        />
    }
    fileName={`${t('filename')} ${successfulPayment.negotiationCode}`}
>
...
```

**2. Translator as a prop:**

```
...
const ReceiptPdf = ({
  paymentData,
  formatValueToMonetary,
  formatDate,
  translator,
}: IReceiptPdfProps) => {
...
```

### This solved the problem, because the **hook was generating a new rendering with each language change and the PDF was not handling it well**.

I hope it helps anyone who has had a similar problem, as this one took me two days of investigation :)

**Comment by mariansimecek** [comment]
Not sure if I have the same error `TypeError: Eo is not a function`, but I found that I accidentally passed a Date as the key for the `<View/>` component.  Maybe this will help someone.

**Comment by VladSez** [comment]
> I have this problem too. React 19.0.0 Issue appears when I use && operator for conditional render and content should dissapear or when I remove some element from array map.
> 
> `{ telegram && ( <Text style={styles.someStyles}>{telegram}</Text>)}` or `{ employments.map((employment, idx) => (<View key={idx} style={styles.someStyles}>{employment}</View>))}`

I receive this error `Error: Eo is not a function` after updating to next 15, I think most likely to conditional render, because when I click checkbox to hide some text on the pdf I get this error `Error: Eo is not a function`

```
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "next": "15.2.2",
```

**Comment by Nizvan018** [comment]
I am having the same issue with `Eo is not a function`, this is my code:

```ts
// Limpia al archivo PDF
    const cleanPDF = () => {
        if (period == "semanal") {
            const document = <WeekAttendancePDF employees={[]} works={[]} weekDays={weekDays} selectedFront={selectedFront} />
            updatePDF(document);
        } else {
            if (!isValid(parseISO(selectedDate))) {
                toast.warning("Por favor, seleccione una fecha válida");
                return;
            }

            const document = <DailyAttendancePDF employees={[]} works={[]} selectedFront={selectedFront} selectedDate={selectedDate} />
            updatePDF(document);
        }

        setChangesInPDF();
    }

    // Aplica el filtro, orden y la fecha al documento
    const setChangesInPDF = () => {
        const filteredAndSortedList = [...employees.filter(filterEmployeesByFront).sort(sortList)];

        if (period == "semanal") {
            const document = <WeekAttendancePDF employees={filteredAndSortedList} works={[selectedWorkName, ...extraSelectedWorkNames]} weekDays={weekDays} selectedFront={selectedFront} />
            updatePDF(document);
        } else {
            const document = <DailyAttendancePDF employees={filteredAndSortedList} works={[selectedWorkName, ...extraSelectedWorkNames]} selectedFront={selectedFront} selectedDate={selectedDate} />
            updatePDF(document);
        }

        setIsModalVisible(true);
    }
```

I had to add a clean fuction and then an update function because when I change the order of the list of elements that is showed with a map in the pdf, the elements get duplicated, ant this was working fine for me util I update to Next.js 15, now I am getting `Eo is not a function` when I generate my PDF and then I change the order of the list and I try to generate the PDF again

**Comment by chiragthummar** [comment]
> This error is because of change in state. I fixed it by doing conditional rendering.

This can be solve by conditionally rendering the PDFViewer rather directly showing through the <div>.

Here is my code of conditional rendering. `<Invoice2 />` is my `PDFViewer` element.


```
"use client";

import { Close } from "@mui/icons-material";
import { Dialog, DialogTitle, IconButton, Slide } from "@mui/material";
import { TransitionProps } from "@mui/material/transitions";
import React from "react";
import Invoice2 from "../invoice/invoice";

const Transition = React.forwardRef(function Transition(
  props: TransitionProps & {
    children: React.ReactElement<any, any>;
  },
  ref: React.Ref<unknown>
) {
  return <Slide direction="up" ref={ref} {...props} />;
});

const TemplateDialog = () => {
  const { open, openCloseDialog } = React.useContext(
    Context
  ) as ContextType;

  return open ? (
    <Dialog
      fullScreen
      open={open}
      onClose={() => openCloseDialog(false)}
      TransitionComponent={Transition}
      keepMounted
    >
      {/* Content */}
      <div className="flex flex-col sm:flex-row w-full min-h-[85%] bg-white">
        {/* Preview */}
        <div className="w-full h-full sm:w-[65%] p-32 overflow-y-scroll sm:flex">
          <Invoice2 />
        </div>
        {/* Template */}
        <div className="w-full sm:w-[35%]">
          <DialogTitle>
            Crop Profile
            <IconButton
              aria-label="Close"
              onClick={() => openCloseDialog(false)}
              sx={{
                position: "absolute",
                top: 8,
                right: 8,
                color: (theme) => theme.palette.grey[500],
              }}
            >
              <Close />
            </IconButton>
          </DialogTitle>

          <div className="p-24 sm:flex-wrap flex z-10 sm:items-center sm:justify-center"></div>
          <div className="w-full items-center justify-around flex p-6">
            <button type="button" className="main-hero-btn sm:ms-8 w-full">
              Checkout
            </button>
          </div>
        </div>
      </div>
    </Dialog>
  ) : (
    <div></div>
  );
};

export default TemplateDialog;
```


My Config.

package.json


```
{
  "name": "",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@ag-media/react-pdf-table": "^2.0.0",
    "@emotion/react": "^11.14.0",
    "@emotion/styled": "^11.14.0",
    "@mui/icons-material": "^5.2.5",
    "@mui/material": "^5.2.5",
    "@mui/x-date-pickers": "^7.28.0",
    "@react-pdf/fns": "3.0.0",
    "@react-pdf/font": "3.0.1",
    "@react-pdf/image": "3.0.1",
    "@react-pdf/layout": "4.2.0",
    "@react-pdf/pdfkit": "4.0.0",
    "@react-pdf/png-js": "3.0.0",
    "@react-pdf/primitives": "4.0.0",
    "@react-pdf/reconciler": "1.1.3",
    "@react-pdf/render": "4.0.2",
    "@react-pdf/renderer": "4.1.6",
    "@react-pdf/stylesheet": "5.2.0",
    "@react-pdf/textkit": "5.0.1",
    "@react-pdf/types": "2.7.0",
    "@types/react-slick": "^0.23.13",
    "dayjs": "^1.11.13",
    "html2canvas": "^1.4.1",
    "jspdf": "^2.5.2",
    "next": "15.2.3",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-easy-crop": "^5.4.1",
    "react-icons": "^5.5.0",
    "react-slick": "^0.30.3",
    "slick-carousel": "^1.8.1"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@formkit/auto-animate": "^0.8.2",
    "@tailwindcss/postcss": "^4",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^9",
    "eslint-config-next": "15.2.3",
    "tailwindcss": "^4",
    "typescript": "^5"
  }
}
```

**Comment by Nizvan018** [comment]
Hi!, I found a solution if anyone encounters the issue with `Eo is not a function`, in my case, the problem arose when updating to Next.js 15. The `updatePDF()` function from `usePDF` was throwing an error. I understand that there might be some conflict when updating the document instance. After researching, I discovered that I can render my PDF from an API route. So, here’s my solution:  

This is the API route:
```ts
export async function POST(req: NextRequest): {
    try {
        const { employee, history, outtings } = await req.json()

        const pdfBuffer = await renderToBuffer(EmployeeHistoryReportPDF({
            employee,
            history,
            outtings
        }));

        return new NextResponse(pdfBuffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename=Reporte.pdf`
            }
        })
    } catch (error: any) {
        return NextResponse.json({ error: "Ha ocurrido un error inesperado al generar el reporte", message: error.message }, { status: 500 });
    }
}
```

And this is how I download the document:
```ts
const res = await fetch("/api/reports/pdf/employeeHistory", {
    method: "POST",
    headers: {
        "Content-Type": "application/json"
    },
    body: JSON.stringify({
        employee,
        history,
        outtings: employee.salidas
    })
});

if (res.status !== 200) {
    const error = await res.json();
    console.error(error.error);

    return Promise.reject(new Error(error.error));
}

const buffer = await res.blob();
saveAs(buffer, `HISTORIAL DE ${employee.no_control} ${employee.nombre} ${employee.apellido_p} ${employee.apellido_m ?? ""}.pdf`);
```

Actually is very simple, I just used the `renderToBuffer` function, and the problems when I try to update the content (like a list of items) is fiexed, because when the API is called it creates a new instance of the document, eliminating the problem of updating the document. I save the document using `saveAs` but it's not necessary.

I hope it can be useful to someone :D

**Comment by harsh7800** [comment]
i was getting the same error ` Eo is not a function` while using `PDFDownloadLink `, this is how i solved it

`const handleDownload = async () => {
    let url = "";
    try {
      const blob = await pdf(
        <InvoicePDF
          selectedInvoice={selectedInvoice}
          invoiceItems={invoiceItems}
        />
      ).toBlob();
      url = URL.createObjectURL(blob);

      const response = await fetch(url);
      const blobData = await response.blob();
      const blobUrl = window.URL.createObjectURL(blobData);

      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `${selectedInvoice.invoice_number}.pdf`;
      link.click();
    } catch (error) {
      console.error("Error in download process:", error);
    } finally {
      if (url) URL.revokeObjectURL(url);
    }
  }`

Hope this helps someone

**Comment by VladSez** [comment]
Hey @diegomura , is it possible for you to fix? 🙏https://github.com/diegomura/react-pdf/issues/2978#issuecomment-2769751410

Because we can’t upgrade to React 19 or Next 15 otherwise🥲

**Comment by MariuzM** [comment]
Wrapping Document in useMemo fixed for me 

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/2251f00c-6e08-4e0d-ba07-78ce844909a0" />

<img width="636" alt="Image" src="https://github.com/user-attachments/assets/83c15174-e39f-40ae-820b-9507757f3737" />

**Comment by AsadSaleh** [comment]
> I fixed my errors by removing the `PDFDownloadLink` component and recreating its functionality by using the following handler:
> 
>     import { pdf } from "@react-pdf/renderer";
> 
>     const handleDownload = async () => {
>     let url = "";
>     try {
>       const blob = await pdf(<ResumePDF data={resumeData} />).toBlob();
>       url = URL.createObjectURL(blob);
> 
>       const response = await fetch(url);
>       const blobData = await response.blob();
>       const blobUrl = window.URL.createObjectURL(blobData);
> 
>       const link = document.createElement("a");
>       link.href = blobUrl;
>       link.download = `resume-${Date.now()}.pdf`;
>       link.click();
> 
>     } catch (error) {
>       console.error("Error in download process:", error);
>     } finally {
>       if (url) URL.revokeObjectURL(url);
>     }

Thanks you saved my project, haha 😄

**Comment by bekizod** [comment]
i have used const handleDownload = async () => {
    let url = "";
    try {
      const blob = await pdf(
        <QuotationPDF
          data={data}
          translations={translations}
          currentLocale={currentLocale}
          logo={logo}
        />
      ).toBlob();
      url = URL.createObjectURL(blob);

      const response = await fetch(url);
      const blobData = await response.blob();
      const blobUrl = window.URL.createObjectURL(blobData);

      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = `resume-${Date.now()}.pdf`;
      link.click();
    } catch (error) {
      console.error("Error in download process:", error);
    } finally {
      if (url) URL.revokeObjectURL(url);
    }
  };


but the error TypeError: Ro is not a function cames what does this means

**Comment by codebravotech** [comment]
I have a super simple page where I render a PDFViewer (bascially view only, no interactive elements besides the pdf viewer itself, i'm using it for a simple demo page of a feature for serializing Sanity Portable Text to ReactPDF components). 

Whenever I would save a code change, the pdf viewer would break until I reload the browser.

Wrapping in useMemo did not work for me - I borrowed a workaround and gave the PDFViewer a key based on the current Date: https://github.com/diegomura/react-pdf/issues/3153. In my simple case that solved it and hasn't caused any other issues.

**Comment by ghost** [comment]
1 of 1 error
Next.js (14.2.16) is outdated [(learn more)](https://nextjs.org/docs/messages/version-staleness)

Unhandled Runtime Error
TypeError: render is not a function

Call Stack
React    


Hi, I read the chat list but I still couldn't fix the problem.

**Comment by benjick** [comment]
I solved it by putting a key on the `PDFDownloadLink` component with all the options that I pass down to it:

```
key={`${taskName}-${taskId ?? "draft"}-${orientation}-${selectedColumns.join("-")}`}
```
