### ISSUE TITLE
@react-pdf/textkit has dependency on babel-runtime & @babel runtime causing it to pick up corejs 3 as though it were corejs 2 which throws an error

### ISSUE THREAD

**Issue by Bored0ne** [diegomura/react-pdf#670]
**Describe the bug**
Basically having react-pdf in the browser and not having core-js 2 available for it to grab causes a dependency to break in @babel-runtime.

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Have the corejs 3 setup on your local react project.
2. Add react-pdf.
3. Try to serve.

**Expected behavior**
It shouldn't fail out

**Screenshots**
![image](https://user-images.githubusercontent.com/8540806/61974443-24507880-afac-11e9-8e44-db9611d3786f.png)

**Desktop (please complete the following information):**
Windows
Chrome
React-pdf 1.6.3

**Comment by ceporche** [comment]
This issue is blocking me from using react-pdf in my project.
@diegomura Could you please have a look at this pr on textkit ?
https://github.com/react-pdf/textkit/pulls
It removes the old babel-runtime dependency, then upgrading the version used in @react-js/rendering should fix the issue.

**Comment by knoopx** [comment]
Adding a resolve alias in webpack allowed me to use it:

```
    resolve: {
      alias: {
        // fix: @reactpdf/textkit redundant dependency on babel-runtime
        "babel-runtime": "@babel/runtime",
      }
```

However the issue is still pretty annoying.

**Comment by ceporche** [comment]
Thanks a lot, it resolves the build issues but I have runtime error afterward in node-fetch
![image](https://user-images.githubusercontent.com/63005817/78763981-2d407900-7986-11ea-8973-5b1a28332938.png)
![image](https://user-images.githubusercontent.com/63005817/78764047-4812ed80-7986-11ea-9593-7cc805d18760.png)
Did you encounter this as well?

**Comment by diegomura** [comment]
Fixed https://github.com/react-pdf/textkit/pull/8/
